source 'https://github.com/palpatim/development-specs.git'

platform :ios, '9.0'
use_frameworks!

target 'TranscribeStreamingExampleWSSObjC' do
  $awsVersion = '~> 2.11.0'
  pod 'AWSTranscribeStreaming', $awsVersion
end
