source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

target 'PhotoAlbum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for PhotoAlbum
  pod 'AWSMobileClient', '~> 2.11.0'
  pod 'AWSUserPoolsSignIn', '~> 2.11.0'
  pod 'AWSAuthUI', '~> 2.11.0'
  pod 'AWSS3', '~> 2.11.0'
  pod 'AWSAppSync', '~> 2.14.3'

  # Tools
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
  
  target 'PhotoAlbumUITests' do
    use_frameworks!
  end
end
