# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'

target 'PinpointSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinpointSample
  pod 'AWSPinpoint', :git => 'https://github.com/zhinang-amazon/aws-sdk-ios.git', :branch => 'pinpointJourneyPush'
  pod 'AWSMobileClient', '~> 2.13.0'
  
  # Tools
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'

end
